### ISSUE TITLE
Instrumenting production build

### ISSUE THREAD

**Issue by tudorgergely** [cypress-io/instrument-cra#135]
Hey! Really awesome project you've got here.

I have one question though: why is this only supported for a development build and not prod?
I'd like to run this with react-scripts build: `react-scripts -r @cypress/instrument-cra build` but it currently fails because of these lines:

```
if (envName !== 'development') {
  throw new Error(
    'Can overwrite cra webpack config only for development environment'
  )
}
```

Do you think running this in production might be supported?

**Comment by penx** [comment]
+1

We are running Cypress in a CI environment with this plugin. Webpack dev server seems to cause Cypress to use up a lot of memory when running specs that have a lot of tests, causing the "We detected that the Chromium Renderer process just crashed" error, detailed in https://docs.cypress.io/guides/references/error-messages.html#The-Chromium-Renderer-process-just-crashed and https://github.com/cypress-io/cypress/issues/349.

I can replicate the memory issues locally without any code instrumentation (with Cypress taking 4GB of RAM) and they are resolved when I run against tests against a production build (setting "numTestsKeptInMemory": 0 also seems to help, I think both are needed).

This means, in order to run code coverage checks in our CI environment, I need a way to instrument the production build.

I will take a look in to doing this manually.

**Comment by penx** [comment]
I have reduced memory usage and added instrumentation to the production build by: 

1. Using an environment variable `COVERAGE=true` to enable instrumentation 
2. Adding `babel-plugin-instabul` as a devDependency
3. Using [craco](https://github.com/gsoft-inc/craco) with the following configuration:

```js
babel: {
	plugins: [
		// any other plugins
		...(process.env.COVERAGE === 'true' ? ['istanbul'] : []),
	],
},
```
4. In `cypress/plugins/index.js`, adding:
```js
if (process.env.COVERAGE === 'true') {
	require('@cypress/code-coverage/task')(on, config);
}
```
5. Setting `CYPRESS_numTestsKeptInMemory=0` on CI

**Comment by penx** [comment]
It would be good to be able to do this without having to use craco, i.e. via `@cypress/instrument-cra`, though I see why the flag is in there to stop people adding instrumentation to their production code.

Perhaps if a check for `process.env.CYPRESS_INSTRUMENT_PRODUCTION==='true'` to allow this protection to be overridden?

**Comment by penx** [comment]
This should do it but I haven't tested it https://github.com/cypress-io/instrument-cra/pull/162
